title: Pavan Kumar Reddy Kancharla
logo: "/profile.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
 Cyber Security Engineer
    <br><br>
    <a href="pavankumarreddykancharla@gmail.com">pavankumarreddykancharla@gmail.com</a>
    <br>
show_downloads: false
theme: jekyll-theme-minimal
